apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  name: regcred
data:
  .dockerconfigjson: {{ .Values.imagePullCredentials | toJson | b64enc }}
